# Generated by Django 5.1.7 on 2025-03-09 17:04

import detection.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DetectionImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to=detection.models.detection_upload_path),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "result_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="detection_results"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DetectionVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "video",
                    models.FileField(upload_to=detection.models.detection_upload_path),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "result_video",
                    models.FileField(
                        blank=True, null=True, upload_to="detection_results"
                    ),
                ),
            ],
        ),
    ]
